### ISSUE TITLE
Dropdown not working on /# path

### ISSUE THREAD

**Issue by parth-paradkar** [iit-technology-ambit/pwa#19]
When an article is clicked(Reaad more), the app redirercts to /# in which dropdown raises the following error
![issue1](https://user-images.githubusercontent.com/45004153/62825072-8b347b00-bbc3-11e9-8e2b-9a48fd4fcfa7.png)

**Comment by rakaar** [comment]
@thescriptninja , we have solved it. Hope this can closed  now !

**Comment by parth-paradkar** [comment]
Cool :+1:
