### ISSUE TITLE
Issue Month and Year not visible in firefox

### ISSUE THREAD

**Issue by rakaar** [iit-technology-ambit/pwa#58]
On hovering the issue, month and year are displayed in chrome but doesn't work in mozilla. This might be due to non supportability of text gradient in firefox. Find an alternate way to use gradient text for browser compatibility.

**Comment by rakaar** [comment]
This is something we forgot. Firefox is an equally important browser. Here are some sites where I found say firefox doesn't support text gradient and if we want to requires some heavy plugin as per [this](https://stackoverflow.com/questions/20790742/text-gradient-on-firefox) and check [this](https://www.webdesignerforum.co.uk/topic/59521-css3-text-gradient-in-firefox-possible/) also.
I prefer we use simple colored text with a different font. @ajajaj2807, @thescriptninja   any suggestions. @thealphadollar  what do you say?

**Comment by thealphadollar** [comment]
Yes, I would say let's switch to coloured text.
