### ISSUE TITLE
Article Component

### ISSUE THREAD

**Issue by rakaar** [iit-technology-ambit/pwa#8]
Each article will have `title`, `text`, `title-image` and `content`, also `ratings from 1-5`, `Comments`. Create a compnent by name Article for that purpose.

**Comment by parth-paradkar** [comment]
Tags will also be displayed at the bottom

**Comment by rakaar** [comment]
@ajajaj2807  is doing this currently.

**Comment by rakaar** [comment]
@ajajaj2807  three more emoji's in the feedback of the article. Also the thing of `visit archive` and `get in touch` is not necesary, I think. And also, the `subscribe` things feels unncessary. 
Author, views and date font is small. Please change it

**Comment by rakaar** [comment]
@ajajaj2807 .
also add save option at the end of the article

**Comment by rakaar** [comment]
@ajajaj2807  the current design is awesome. Just one more small request. 
Please make it mobile responsive. I can do it but it will take more time for me than you as you wrote  it's code. 

Also remove get in touch line, and visit archive lines

**Comment by rakaar** [comment]
Save and share button are not mobile responsive. please make it mobile responsive @ajajaj2807
